apiVersion: apps/v1
kind: Deployment
metadata:
  name: streampod-player
spec:
  selector:
    matchLabels:
      run: streampod-player
  replicas: 2
  template:
    metadata:
      labels:
        run: streampod-player
    spec:
      containers:
      - name: streampod-player-pod
        image: ocano/streampod_player
        ports:
        - containerPort: 80

## Simple Prototype Deployment - ocano 6/16/21
## Supports ECR images.